[workspace]
members = [
	"dof",
	"dtrace-parser",
	"dusty",
	"probe-test-build",
	"probe-test-macro",
	"tests/compile-errors",
	"tests/empty",
	"tests/namespace-conflict",
	"tests/zero-arg-probe",
	"usdt",
	"usdt-impl",
	"usdt-macro"
]
default-members = [
	"dof",
	"dtrace-parser",
	"usdt",
	"usdt-impl",
	"usdt-macro"
]
