[package]
name = "dtrace-parser"
version = "0.1.10"
authors = ["Benjamin Naecker <ben@oxidecomputer.com>",
           "Adam H. Leventhal <ahl@oxidecomputer.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Parse DTrace provider definitions into Rust"
repository = "https://github.com/oxidecomputer/usdt.git"

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
thiserror = "1.0.24"
syn = { version = "1.0.60", features = ["full"] }

[dev-dependencies]
rstest = "0.6.4"
